cargo-features = ["edition2024"]

[package]
name = "ast"
version = "0.1.0"
authors = ["Devin Alexander Torres <d@devinus.io>"]
license = "0BSD"
edition = "2024"

[dependencies]
syntax = { path = "../syntax" }
text-size = "1.1.1"

[dev-dependencies]
parser = { path = "../parser" }
