cargo-features = ["edition2021"]

[package]
name = "lexer"
version = "0.1.0"
authors = ["Devin Alexander Torres <d@devinus.io>"]
license = "0BSD"
edition = "2021"

[dependencies]
logos = "0.12.0"
logos-derive = "0.12.0"
text-size = "1.1.0"
