[package]
name = "syntax"
version = "0.1.0"
authors = ["Devin Alexander Torres <d@devinus.io>"]
license = "MIT-0"
edition = "2024"

[dependencies]
lexer = { path = "../lexer" }
num-derive = "0.4.2"
num-traits = "0.2.19"
rowan = "0.16.1"
