[package]
name = "syntax"
version = "0.1.0"
authors = ["Devin Alexander Torres <d@devinus.io>"]
license = "0BSD"
edition = "2021"

[dependencies]
lexer = { path = "../lexer" }
num-derive = "0.4.0"
num-traits = "0.2.16"
rowan = "0.15.11"
